### ISSUE TITLE
[Bug]: Oops! useActionData must be used within a data router. On document load with useForm - on document initial load

### ISSUE THREAD

**Issue by blorenz** [airjp73/rvf#410]
### Which packages are impacted?

- [ ] `@rvf/react`
- [X] `@rvf/react-router`
- [X] `@rvf/zod`
- [ ] `@rvf/yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

   ```"@react-router/node": "^7.0.2",
    "@react-router/serve": "^7.0.2",
    "@rvf/core": "^7.0.1",
    "@rvf/react-router": "^7.0.1",
    "@rvf/zod": "^7.0.1",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-router": "^7.0.2"
```

### Please provide a link to a minimal reproduction of the issue.

copy and paste in steps to reproduce

### Steps to Reproduce the Bug or Issue

1. `npx create-react-router@latest rvf-rr7`
2. install latest rvf
3. Replace home.tsx with this content:
```
import type { Route } from "./+types/home";
import { Form } from 'react-router';
import { useForm } from '@rvf/react-router';
import { withZod } from '@rvf/zod';
import { z } from 'zod';

export function meta({}: Route.MetaArgs) {
  return [
    { title: "New React Router App" },
    { name: "description", content: "Welcome to React Router!" },
  ];
}

export async function action({
  request,
}: Route.ActionArgs) {
  let formData = await request.formData();
  return "hello world";
}
export default function Home() {
  const id = 'test';
  const form = useForm({
    id,
    validator: withZod(z.object({})),
    defaultValues: {},
    method: 'POST',
  });
  return <div className={"flex flex-col gap-y-8"}>
    <Form {...form.getFormProps()} />
  </div>;
}

```
4. Navigate to home on a document load and receive error.

### Expected behavior

I would expect the page to render on document initial load.

### Platform

macOS, Chrome, latest

**Comment by airjp73** [comment]
Hi!

The issue doesn't reproduce when I follow those steps. Could you provide a Code sandbox (or similar) instead that contains the issue?

**Comment by ZipBrandon** [comment]
@airjp73 I attempted to recreate with Stackblitz even though they only have node 18 and RR needs 20.  It worked as expected. I then tested against node 20 and node 22 locally.  The issue is node 23 it seems. I'll rollback to node 22 personally. 

I wonder why rr7/other libs worked fine with 23 and rvf had an issue?

**Comment by airjp73** [comment]
Thanks for looking into that! My best guess is a change to dependency resolution in npm somehow causing rvf to resolve a different version of RR than the rest of the app. But I won't have time to test that hypothesis until at least tomorrow. 

What happens when you `npm ls react-router` on node 23?

**Comment by ZipBrandon** [comment]
Unfortunately ,it is all rr 7.0.2.
```├─┬ @react-router/dev@7.0.2
│ └── react-router@7.0.2 deduped
├─┬ @react-router/node@7.0.2
│ └── react-router@7.0.2 deduped
├─┬ @react-router/serve@7.0.2
│ ├─┬ @react-router/express@7.0.2
│ │ └── react-router@7.0.2 deduped
│ └── react-router@7.0.2 deduped
├─┬ @rvf/react-router@7.0.1
│ └── react-router@7.0.2 deduped
└── react-router@7.0.2
```
![image](https://github.com/user-attachments/assets/fcfbb5ac-6248-4501-bf10-0d1f3905e0a0)

**Comment by airjp73** [comment]
The react-router repo has an issue [here](https://github.com/remix-run/react-router/issues/12475) that looks related.

**Comment by miran248** [comment]
Don't know, what's causing the error but i *solved* it by downgrading vite from `6.0.6` to `5.4.11` (all other deps are *latest*).

**Comment by xealot** [comment]
I had this issue as well, moving Vite from 6.x to 5.x like @miran248 also fixed it for me.

**Comment by vrn-hkz** [comment]
Updating to node v22.13.0 fixed this for me. My package.json:

```
"dependencies": {
		"@react-router/node": "^7.1.1",
		"@react-router/serve": "^7.1.1",
		"@rvf/react-router": "^7.0.1",
		"@rvf/zod": "^7.0.1",
		"isbot": "^5.1.21",
		"react": "^19.0.0",
		"react-dom": "^19.0.0",
		"react-router": "^7.1.1",
		"zod": "^3.24.1"
	},
	"devDependencies": {
		"@react-router/dev": "^7.1.1",
		"@types/bun": "latest",
		"@types/node": "^22",
		"@types/react": "^19.0.4",
		"typescript": "^5.7.3",
		"vite": "^6.0.7",
		"vite-tsconfig-paths": "^5.1.4"
	},
```

**Comment by justinwaite** [comment]
The issue persists for me. I'm using tsx in dev-mode with my custom server. I've tried node 22.12 and node 22.13. I've also tried using vite 5 and 6. None of these combinations work. I've also used resolutions to ensure rr 7.1.3 is being used, and pnpm ls shows that i only have one version of RR installed.

**Comment by dziugas-liaudinskas** [comment]
I have the same issue. Any updates or solutions?

**Comment by airjp73** [comment]
Even though the initial react router issue is solved, it looks like there's another open one here: https://github.com/remix-run/react-router/issues/12785

There's a potential workaround mentioned in one of the recent comments. Does that fix it for anyone?

**Comment by Charioteer** [comment]
Hi all, hi @airjp73,

I had the same issue and just tried to fix it with the suggested workarounds in various remix/react-router issues. For me, it only worked to manually remove the `module-sync` export from `node_modules/react-router/package.json` as suggested e.g. [here](https://github.com/remix-run/react-router/issues/12475#issuecomment-2578174224).

I've patched it with `pnpm patch` for now to move on.

**Comment by airjp73** [comment]
Is this issue still occurring? Or are the workarounds at least pretty reliable? It looks like the react-router issue is still open.

**Comment by Crauzer** [comment]
Yes this issue still persists even on Node v22.20.0 and latest react-router version

**Comment by Mause** [comment]
This still seems to be an issue for me as well, with `react-router@7.14.2` and `@rvf/react-router@8.1.2`

**Comment by Crauzer** [comment]
Yeah at this point I'd just recommend that people switch to using TanStack Form or Conform instead of this library.
We had to migrate all of our forms to Conform as this was causing a lot of issues in production.

**Comment by kennygoff** [comment]
I am still seeing this issue, but only in vitest @airjp73. The workaround is buried in a few different issues, if anyone else is looking for it: https://github.com/remix-run/react-router/issues/12785#issuecomment-2731496414

**Comment by aaschlote** [comment]
I have updated to `react-router` 8 and I'm getting the same issue. Even using `conditions: ["module-sync"],` doesn't work.

Maybe in my case it's only a problem with the synch between this dependency and the new major version of react-router.

@airjp73 Any ideas?

Below the error stack trace:

```
Error: useActionData must be used within a data router.  See https://reactrouter.com/en/main/routers/picking-a-router.
    at invariant (file:///Users/aschlote/Developer/a2j-rechtsantragstelle/node_modules/.pnpm/react-router@8.0.1_react-dom@19.2.7_react@19.2.7/node_modules/react-router/dist/production/lib/router/history.js:189:79)
    at useDataRouterState (file:///Users/aschlote/Developer/a2j-rechtsantragstelle/node_modules/.pnpm/react-router@8.0.1_react-dom@19.2.7_react@19.2.7/node_modules/react-router/dist/production/lib/hooks.js:804:2)
    at useActionData (file:///Users/aschlote/Developer/a2j-rechtsantragstelle/node_modules/.pnpm/react-router@8.0.1_react-dom@19.2.7_react@19.2.7/node_modules/react-router/dist/production/lib/hooks.js:1013:14)
    at useErrorResponseForForm (/Users/aschlote/Developer/a2j-rechtsantragstelle/node_modules/.pnpm/@rvf+react-router@8.1.2_@types+react@19.2.17_react-dom@19.2.7_react-router@8.0.1_react@_120b9abda2b97283b3d2970a6ed56ad2/node_modules/@rvf/react-router/src/auto-server-hooks.tsx:13:22)
    at useServerValidationErrors (/Users/aschlote/Developer/a2j-rechtsantragstelle/node_modules/.pnpm/@rvf+react-router@8.1.2_@types+react@19.2.17_react-dom@19.2.7_react-router@8.0.1_react@_120b9abda2b97283b3d2970a6ed56ad2/node_modules/@rvf/react-router/src/auto-server-hooks.tsx:35:28)
    at useForm (/Users/aschlote/Developer/a2j-rechtsantragstelle/node_modules/.pnpm/@rvf+react-router@8.1.2_@types+react@19.2.17_react-dom@19.2.7_react-router@8.0.1_react@_120b9abda2b97283b3d2970a6ed56ad2/node_modules/@rvf/react-router/src/useForm.tsx:98:23)
    at ValidatedForm (/Users/aschlote/Developer/a2j-rechtsantragstelle/node_modules/.pnpm/@rvf+react-router@8.1.2_@types+react@19.2.17_react-dom@19.2.7_react-router@8.0.1_react@_120b9abda2b97283b3d2970a6ed56ad2/node_modules/@rvf/react-router/src/ValidatedForm.tsx:114:15)
```

**Comment by aaschlote** [comment]
Any feedback for this problem? We can't update our project to react-router 8.
